apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: llama-workflow-
  namespace: argo
  labels:
    workflows.argoproj.io/workflow: "true"
    workflows.argoproj.io/workflow-template: llama-workflow
spec:
  arguments:
    parameters:
    - name: trainThreshold
      value: "1.0"
    - name: trainImage
      value: "phajder/llama2-ph"
    - name: trainTag
      value: "0.2-train"
    - name: evalImage
      value: "phajder/llama2-ph"
    - name: evalTag
      value: "0.2-eval"
    - name: fakeLoadImage
      value: "phajder/llama2-ph"
    - name: fakeLoadTag
      value: "0.2-load"
    - name: datasetHostPath
      value: "/home/phajder/datasets"
    - name: checkpointsHostPath
      value: "/home/phajder/checkpoints"
    - name: modelsHostPath
      value: "/home/phajder/models"
  workflowTemplateRef:
    name: llama-workflow
