apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-workflow-templates
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: "https://kubernetes.default.svc"
  source:
    path: infra/workflow-templates
    repoURL: "https://github.com/phajder/llama-argocd"
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=background
      - CreateNamespace=true
