apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: eval-job
spec:
  # volumes:
  # - name: checkpoints
  #   hostPath:
  #     path: "{{workflow.parameters.checkpointsHostPath}}"
  # - name: models
  #   hostPath:
  #     path: "{{workflow.parameters.modelsHostPath}}"
  entrypoint: main
  templates:
  - name: main
    container:
      image: "{{workflow.parameters.evalImage}}:{{workflow.parameters.evalTag}}"
      imagePullPolicy: Always
      volumeMounts:
      - name: checkpoints
        mountPath: "{{workflow.parameters.checkpointsPath}}"
        readOnly: true
      - name: models
        mountPath: "{{workflow.parameters.modelsPath}}"
      env:
      - name: LOG_PATH
        value: "{{workflow.parameters.logDir}}"
      - name: CHECKPOINTS_PATH
        value: "{{workflow.parameters.checkpointsPath}}"
      - name: MODELS_PATH
        value: "{{workflow.parameters.modelsPath}}"
    outputs:
      parameters:
      - name: result
        valueFrom:
          path: /tmp/output.txt
