apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fake-load-job
spec:
  # volumes:
  # - name: models
  #   hostPath:
  #     path: "{{workflow.parameters.modelsHostPath}}"
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: modelFilename
    container:
      image: "{{workflow.parameters.fakeLoadImage}}:{{workflow.parameters.fakeLoadTag}}"
      imagePullPolicy: Always
      volumeMounts:
      - name: models
        mountPath: "{{workflow.parameters.modelsPath}}"
      env:
      - name: LOG_PATH
        value: "{{workflow.parameters.logDir}}"
      - name: MODELS_PATH
        value: "{{workflow.parameters.modelsPath}}"
      - name: MODEL_FILENAME
        value: "{{inputs.parameters.modelFilename}}"
