apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- fetch-dataset.yaml
- train.yaml
- notify-failure.yaml
- eval.yaml
- fake-load.yaml
- upload-model.yaml
- serve.yaml
- llama-workflow.yaml