apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: llama-workflow
spec:
  volumes:
  - name: dataset
    hostPath:
      path: "{{workflow.parameters.datasetHostPath}}"
  - name: checkpoints
    hostPath:
      path: "{{workflow.parameters.checkpointsHostPath}}"
  - name: models
    hostPath:
      path: "{{workflow.parameters.modelsHostPath}}"
  entrypoint: llama-workflow
  arguments:
    parameters:
    - name: logDir
      value: "/var/log"
    - name: trainThreshold
      value: "1.0"
    - name: datasetPath # Dataset path inside container
      value: "/app/dataset"
    - name: checkpointsPath # Checkpoints path inside container
      value: "/app/checkpoints"
    - name: modelsPath # Models path inside container
      value: "/app/models"
    - name: trainImage
      value: ""
    - name: trainTag
      value: ""
    - name: evalImage
      value: ""
    - name: evalTag
      value: ""  
    - name: fakeLoadImage
      value: ""
    - name: fakeLoadTag
      value: ""
    - name: datasetHostPath
      value: ""
    - name: checkpointsHostPath
      value: ""
    - name: modelsHostPath
      value: ""
  templates:
  - name: llama-workflow
    dag:
      tasks:
      - name: train
        templateRef:
          name: train-job
          template: main
      - name: eval
        templateRef:
          name: eval-job
          template: main
        depends: train
      - name: fake-load
        arguments:
          parameters:
          - name: modelFilename
            value: "{{tasks.eval.outputs.parameters.result}}"
        templateRef:
          name: fake-load-job
          template: main
        depends: eval
      - name: serve
        templateRef:
          name: serve-deployment
          template: main
        depends: fake-load
      - name: delete-app
        template: delete-app
        depends: (serve.Failed)

  - name: delete-app
    resource:
      action: delete
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: llama-serve
          namespace: argocd
