apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: llama-workflow
spec:
  volumes:
  - name: log
    hostPath:
      path: /var/log
  - name: nfs-dataset
    nfs:
      server: truenas.lan
      path: /mnt/main/train
  - name: nfs-models
    nfs:
      server: truenas.lan
      path: /mnt/main/models
  - name: dataset
    hostPath:
      path: "{{workflow.parameters.datasetHostPath}}"
  - name: checkpoints
    hostPath:
      path: "{{workflow.parameters.checkpointsHostPath}}"
  - name: models
    hostPath:
      path: "{{workflow.parameters.modelsHostPath}}"
  entrypoint: llama-workflow
  arguments:
    parameters:
    - name: logDir
      value: "/var/log"
    - name: trainThreshold
      value: "1.0"
    - name: datasetFilename # Dataset name
      value: dataset.txt
    - name: datasetPath # Dataset path inside container
      value: "/app/dataset"
    - name: checkpointsPath # Checkpoints path inside container
      value: "/app/checkpoints"
    - name: modelsPath # Models path inside container
      value: "/app/models"
    - name: trainImage
      value: ""
    - name: trainTag
      value: ""
    - name: evalImage
      value: ""
    - name: evalTag
      value: ""  
    - name: fakeLoadImage
      value: ""
    - name: fakeLoadTag
      value: ""
    - name: datasetHostPath
      value: ""
    - name: checkpointsHostPath
      value: ""
    - name: modelsHostPath
      value: ""
    - name: discordWebhook
      value: ""
  templates:
  - name: llama-workflow
    dag:
      tasks:
      - name: fetch-dataset
        templateRef:
          name: fetch-dataset
          template: main
      - name: train
        templateRef:
          name: train-job
          template: main
        depends: fetch-dataset
      - name: notify-failure
        arguments:
          parameters:
            - name: message
              value: "Training failed!"
        templateRef:
          name: notify-failure
          template: main
        depends: (train.Failed)
      - name: fail-after-train
        template: fail-workflow
        depends: notify-failure
      - name: eval
        templateRef:
          name: eval-job
          template: main
        depends: train
      - name: upload-model
        arguments:
          parameters:
          - name: modelFilename
            value: "{{tasks.eval.outputs.parameters.result}}"
        templateRef:
          name: upload-model
          template: main
        depends: eval
      - name: fake-load
        arguments:
          parameters:
          - name: modelFilename
            value: "{{tasks.eval.outputs.parameters.result}}"
        templateRef:
          name: fake-load-job
          template: main
        depends: eval
      - name: serve
        arguments:
          parameters:
          - name: modelName
            value: "{{tasks.eval.outputs.parameters.result}}"
        templateRef:
          name: serve-deployment
          template: main
        depends: fake-load
      - name: delete-app
        template: delete-app
        depends: (serve.Failed)

  - name: delete-app
    resource:
      action: delete
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: llama-serve
          namespace: argocd
  - name: fail-workflow
    container:
      image: busybox
      command: [ "sh", "-c" ]
      args: [ "exit 1" ]
