apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: train-job
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: "{{workflow.parameters.trainImage}}:{{workflow.parameters.trainTag}}"
      imagePullPolicy: Always
      volumeMounts:
      - name: dataset
        mountPath: "{{workflow.parameters.datasetPath}}"
        readOnly: true
      - name: checkpoints
        mountPath: "{{workflow.parameters.checkpointsPath}}"
      env:
      - name: LOG_PATH
        value: "{{workflow.parameters.logDir}}"
      - name: DATASET_PATH
        value: "{{workflow.parameters.datasetPath}}"
      - name: CHECKPOINTS_PATH
        value: "{{workflow.parameters.checkpointsPath}}"
      - name: TRAIN_THRESHOLD
        value: "{{workflow.parameters.trainThreshold}}"
